# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-10 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20170627_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='feelings',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='survey',
            name='medications',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='survey',
            name='substances',
            field=models.CharField(default='', max_length=200),
        ),
    ]
